path:
  save_dir: 'output'
  dataset: './data/my_dataset'

seed: 42
train_batch_size: 64
val_batch_size: 16 
train_val_test_ratio: [ 0.8, 0.1, 0.1]
num_epochs: 500
learning_rate: 1e-3
weight_decay: 1e-4

num_workers: 8

data:
  image_size: 64
  channels: 1

loss:
  vae:
    recon_type: "l1"
    beta: 0.1
    kl_reduction: "sum"
    recon_reduction: "sum"

model:
  vae:
    type: "autoencoder_kl"
    autoencoder_kl:
      in_channels: 1
      out_channels: 1
      down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D"]
      up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D"]
      block_out_channels: [32, 64]
      layers_per_block: 1
      act_fn: "silu"
      latent_channels: 4
      norm_num_groups: 32
      sample_size: 64
      scaling_factor: 0.18215
      shift_factor: None
      latents_mean: None
      latents_std: None
      force_upcast: True
      use_quant_conv: True
      use_post_quant_conv: True
      mid_block_add_attention: True
